quipucords/ci

.gitignore, README.md, jjb/requirements.txt, requirements.txt
~~Make it so user can install jjb dependencies in virtualenv with `python
setup.py install`. In the future, if other dependencies are added, they
can be added to setup.py and users can make sure they are using the
right packages and versions easily.~~
Make it so user can install jjb dependencies in virtualenv with `pip
install -r requirements.txt`.
In the future, if other dependencies are added, they can be added to
requirements.txt or jjb/requirements.txt. This will help users make
sure they are using the right packages and versions.
=> Add .gitignore, requirements.txt, update Readme     

jjb/jobs/projects.yaml, jjb/jobs/rho-nightly-remote-scan.yaml
Generates jenkins jobs that run against remote machines using config
files present on jenkins nightly at different times.
Note that we cannot run these in parallel, so we don't use pytest-xdist.
Exactly what tests these jobs performed is determined by the config file present on jenkins.
=> Add job template for remote scan jobs.

jjb/jobs/rho-nightly-remote-scan.yaml
Use the last known good version of ansible for now. Camayoc
needs to use python 3, but there is currently a bug in the 2.4 ansible
release that rho pulls in via pip.
Closes #15
=> Work around ansible 2.4 bug for now

jjb/jobs/qcs-nightly-automation.yaml
This job clones the quipucords/quipucords repo, installs necessary
system packages and installs other requirements via pip.
It uses pytest to run the tests to generate an xml report, and then runs
the coverage report generator.
Closes #13 
@elyezer if you would rather this be a job-template and run this on several types of nodes, let me know. (currently just runs on fedora)
=> Adds job to install qcs and run unit tests

ansible/jboss-eap-install.yaml, ansible/roles/jboss_eap_install/defaults/main.yaml, ansible/roles/jboss_eap_install/meta/main.yaml, ansible/roles/jboss_eap_install/tasks/main.yaml, ansible/roles/jboss_eap_install/templates/jboss_eap.service.j2, ansible/roles/jboss_eap_install/templates/standalone.conf.j2, ansible/roles/setup_jboss_user/defaults/main.yaml, ansible/roles/setup_jboss_user/tasks/main.yml, ansible/roles/subscription-manager/tasks/main.yaml
This branch contains:
* role to register a RHEL machine with subscription manager, optionally using a custom CDN (i.e. our stage environment). 
* role to create a jboss user, install jboss, and install necessary files to run jboss on boot with systemd
I've marked it WIP for now because I  want to get some feed back on the work flow.
Message me and I can provide you with more details on where to get the jboss zip and what variables you need to provide to the subscription manager role.
=> ansible role to install jboss

jjb/jobs/qcs-nightly-automation.yaml
Also makes sure an ssh key file exists to get past file validation
checks, because although we are using the ssh agent, the server wants a
file to be present.
=> Save server logs from qcs job as artifact

ansible/jboss-eap-install.yaml, ansible/roles/jboss_eap_install/defaults/main.yaml, ansible/roles/jboss_eap_install/tasks/main.yaml, ansible/roles/jboss_eap_install/templates/standalone.conf.j2
I fixed up the jboss fuse machine to be installed on jboss enabled via chkconfig. I thought I would record my efforts in this ansible playbook as to save work in the future.
Now by default jboss is installed with chkconfig, and optionally the user can
use systemd.
=> Add ability to install jboss with chkconfig

jjb/jobs/projects.yaml, jjb/jobs/rho-nightly-remote-scan.yaml
After recent changes on Camayoc now the remote scan job is meant to be a
single job which will scan every machine available in the configuration
file's inventory section. Update the rho remote scan job definition to
match this new way of performing the remote scan.
Close #30
=> Update rho remote scan job

jjb/jobs/rho-nightly-remote-scan.yaml
Now that the remote job is not a template, but rather a job in its own right, we don't need to escape the curly braces. In fact, we must not for it to run correctly on Jenkins.
=> Fix curly braces in remote job

jjb/jobs/qcs-nightly-automation.yaml
We need to run the server with authentication disabled until camayoc is
updated to use the token authentication with API and CLI tests.
Closes #39
=> Disable authentication while running quipucords

jjb/jobs/qcs-nightly-automation.yaml
Now that camayoc PR #123
(https://github.com/quipucords/camayoc/pull/123) is closed, we can run
the server without disabling authentication.
=> Run the quipucords server with auth enabled

jjb/jobs/qcs-nightly-automation.yaml
Now that the issue quipucords/camayoc/#110 is closed, rho and quipucords jobs
use the same config file format.
This commit updates the id so both use the same file on Jenkins.
=> Update config file id

jjb/jobs/rho-nightly-remote-scan.yaml
There is now another module underneath `camayoc/camayoc/tests/remote/` 
that does not make sense to run concurrently with the rho tests. 
We must specify the `rho` subdirectory.
=> Update rho nightly scan to only run rho tests

jjb/jobs/qcs-PILOT-nightly-automation.yaml
Also update nightly job testing the lastest container to archive logs and quiet
down the noise in the py.test console output about insecure requests made to
the container.
Closes #53
=> Create nightly job to test pilot package and container

jjb/jobs/projects.yaml, jjb/jobs/qcs-PILOT-container-install.yaml, jjb/jobs/qcs-PILOT-nightly-automation.yaml, scripts/quipucords/pilot/install/test_install.py
Verify install on RHEL 6 and 7 as well as Fedora 27 from github release
tarball.  Adds python 2 compliant install validation test for pilot.
Also updates nightly pilot automation job to use github release image as well.
This job is distinct in that it runs entire camayoc test suite against the container, where as the `qcs-container-install` jobs only verify that the install method was successful.
Closes #50
Closes #56
=> Create jobs to verify install of pilot container

jjb/jobs/qpc-PILOT-nightly-automation.yaml, jjb/jobs/qpc-nightly-automation.yaml
Don't allow nightly jobs to run in parallel since both manage vCenter
vms. Also improve the PILOT nightly automation to be able to scan using
the scan users.
=> Improve qpc nightly jobs

ansible/roles/setup_scan_users/tasks/main.yml
Either install libselinux-python or python3-libselinux depending on the
package available on the repositories.
=> Update setup_scan_users role

jjb/jobs/projects.yaml, jjb/jobs/qpc-container-install.yaml
- Removed the master/release conditionals since the master jobs have been offloaded to their own templates. This template will be used just for releases now.
- Updated release specified to 0.0.46.
- updated quipucords download source
- switched to using install.sh install method instead of manually running the ansible playbooks
=> Remove master condition

jjb/include/pipelines/qpc-release-test-install.groovy, jjb/jobs/projects.yaml, jjb/jobs/released-pipelines-template.yaml
I added a conditional to create/run `nosupervisord` install tests pipelines.
- Broke up the `install.sh` command into two functions in the pipeline code. (one for default install, one for nosupervisord). This can be expanded to more cases in the future by adding more functions.
- The setupQPC() function just calls the appropriate install function based on the conditional (using the `install_type` variable.
- Edited pipeline template/project definition to include the `install_type` variable.
=> Added conditional for nosupervisord install pipelines

jjb/include/pipelines/qpc-tests-pipeline.groovy, jjb/jobs/projects.yaml, jjb/jobs/qpc-templates.yaml
This PR implements a bunch of changes to the testing pipeline. It combines everything into a pipeline so that both installer tests and camayoc tests can be run from the same pipeline file, across all the desired install targets (distros). There are improvements to make still, but this restructures everything so that it is possible.
Features:
- Pipeline runs parallel across targets
- Multiple install methods (`default` install.sh install, `nosupervisord` install.sh install, container install)
- Same pipeline for both `master` and release branches (ex: `0.0.46`. `0.0.47`)
- Creating a job for a new release *should* just require adding the release to the `qpc-release-test-pipeline` project template, and running the jenkins job builder to create it.
- updating master *should* just require …
=> Combine release master pipelines

jjb/jobs/projects.yaml
Added `quipucords-installer` to the build jobs jjb template. 
This template defines jobs that pull and build the `Jenkinsfile` from the various quipucords repos, for both `master` and defined release branches (currently just `0.0.46`).
This change adds the [quipucords-installer repo](https://github.com/quipucords/quipucords-installer) to that list. 
Note: This change job will only work for releases *after* `0.0.46`.
=> Added quipucords-installer builder job template

jenkins/pipelines/test/qpc-test-pipeline.groovy
Also, swapped CLI and API order because CLI runs initial tests quicker
This lets us know if stuff if failing faster.
=> Switched back to using camayoc master branch.

jenkins/pipelines/test/qpc-dsc-test-pipeline.groovy, jenkins/pipelines/test/qpc-dsc-test-wrapper.groovy
Updated the default versions for the tests pipelines to use the `0.9.2` server and `0.9.3` cli versions.
=> Updated defaults version to 0.9.2 for server and 0.9.3 for cli

jenkins/pipelines/test/qpc-dsc-test-pipeline.groovy, jenkins/pipelines/test/qpc-dsc-test-wrapper.groovy
Now that the discovery runs are actually using the version variable, the version number being passed by the wrapper must be updated.
=> Update discovery default versions
