ansible/roles/nodepool/files/elements/jenkins-slave/package-installs.yaml, ansible/roles/nodepool/tasks/main.yaml
Make nodepool Ansible in sync with the current code on the automation
system.
Closes #8
=> Update nodepool Ansible role

jjb/jobs/rho-nightly-automation.yaml, jjb/jobs/rho-nightly-remote-scan.yaml
Only run Camayoc's rho related tests and make sure the SSH key path
exists.
Closes #18
=> Update rho-nightly-automation job

ansible/roles/setup_scan_users/tasks/main.yml
Setup an additional user scanadminpwd which can run sudo but the
password is required. Also add some conditionals to only setup yum repos
and authorize an ssh key when variables are defined. Finally setup RHEL
5 repos if variables are available.
=> Update setup_scan_users role

jjb/jobs/polarion-test-case-importer.yaml
=> Add job to import test cases into Polarion

ansible/roles/setup_scan_users/tasks/main.yml
=> Set authorized key for the scanadminpwd user

jjb/jobs/qcs-nightly-automation.yaml
=> Run qcs-nightly-automation using Python 3.6

jjb/jobs/qcs-nightly-automation.yaml
Run quipucords server from the docker container and installs `qpc`
client using the copr repository.
Close #38
=> Update qcp-nightly-automation job

jjb/jobs/qcs-nightly-automation.yaml
Before running Camayoc edit its config file to edit the jenkins slave IP
address placeholder to the actual jenkins slave IP address.
Close #48
=> Update qcs-nightly-automation job

jjb/jobs/qcs-PILOT-container-install.yaml
Fix stale feature branch reference left in on accident.
=> Fix stale branch reference in pilot install job

jjb/jobs/qpc-container-install.yaml
Copy artifacts from qpc-master and target the proper tarball.
=> Update container install jobs

jjb/include/pipelines/qpc-release-test-install.groovy, jjb/jobs/projects.yaml, jjb/jobs/qpc-container-install.yaml
Added a new pipeline template and project set to run the install tests for releases as a parallel pipeline.
Closes #103
=> Release Install Tests Pipeline

jjb/jobs/projects.yaml, jjb/jobs/qpc-container-install-no-supervisord.yaml
Added a template to test `no_supervisord` installs.
=> Added template for no_supervisord test install jobs

jjb/include/pipelines/qpc-master-test-install.groovy, jjb/include/pipelines/qpc-release-test-install.groovy, jjb/jobs/projects.yaml
Removed the f27 nodes from the pipeline, and also added a Camayoc testing stage to the F28 node (to replace the out-dated nightly f27 automation camayoc jobs).
Closes #111 
Closes #112
=> Remove f27 and Add Camayoc tests

jjb/include/pipelines/qpc-tests-pipeline.groovy
Updated quipucords server container image name to match new build job artifact names.
=> Switched docker image name in test pipeline

jjb/include/pipelines/qpc-tests-pipeline.groovy
Updated project names in artifact pulls to match the new builder job names.
=> Updated build source project names in pipeline

jjb/jobs/projects.yaml
=> Added test pipeline jobs for 0.9.0

jenkins/pipelines/test/qpc-dsc-test-pipeline.groovy
Added another stage that collects the logs from the server's mounted volume after all the tests are run.
Closes #160
=> Added a stage to archive the application logs as an artifact

jenkins/pipelines/test/qpc-dsc-test-wrapper.groovy
Changed some jenkins job names around, and updated the wrapper pipeline to reflect it.
=> Updated pipeline job names in test wrapper pipeline

jenkins/pipelines/test/qpc-dsc-test-wrapper.groovy
Switched to using a generic single pipeline job for both upstream and downstream
=> Test pipeline job renames

jenkins/pipelines/test/qpc-dsc-test-pipeline.groovy
Added an optional parameter to provide a discovery image link. This can be used to run the test pipeline using a test build to check a build before release.
=> Add custom dsc image option
